name: Run Python Tests

on: [push, pull_request] # Trigger the workflow on push and pull request events

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard Linux runner
    strategy:
      matrix:
        python-version: ["3.11"] # Specify the Python version to use

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest

      - name: Run tests with pytest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          pytest